### ISSUE TITLE
ERROR: Failed to resolve: com.github.MSF-Jarvis:AppRate:1.3

### ISSUE THREAD

**Issue by HrnSvnc** [msfjarvis/AppRate#8]
I did add the dependency into my build.gradle file, as i put every dependency in it.

`implementation 'com.github.MSF-Jarvis:AppRate:1.3'`

Did i made a typo or what is wrong with it?

**Comment by msfjarvis** [comment]
Did you are the Jitpack repository?

**Comment by HrnSvnc** [comment]
Stupid me. I'm sorry. it is solved. Thank you very much =)
